ports:
  - port: 8545
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: open-browser
    visibility: public

tasks:
  - name: Run Backend
    init: npm install
    command: |
      npx hardhat node

  - name: Contract Deploy
    command: npx hardhat run scripts/deploy.js --network localhost

  - name: Run Frontend
    init: |
      cd pages
      npm install
    command: |
      cd pages
      npm run dev